apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clinical-backend-metrics
  namespace: api
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: clinical-backend
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - api