apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: clinical-assertion
  namespace: triton
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
spec:
  predictor:
    serviceAccountName: triton-sa
    minReplicas: 1
    maxReplicas: 3
    model:
      modelFormat:
        name: triton
      storageUri: "gs://project-e8b9570a-b660-4f1a-ae2-ml-models/clinical_assertion"
      
      args:
        - --model-repository=/mnt/models
        - --strict-model-config=false
        - --http-port=8080
        - --grpc-port=8001
        - --metrics-port=8002
        - --log-verbose=1
        - --backend-config=onnxruntime,inter_op_thread_count=2
        - --backend-config=onnxruntime,intra_op_thread_count=2
      resources:
        requests:
          cpu: "1000m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
    nodeSelector:
      cloud.google.com/gke-nodepool: cpu-app-pool-v3